In [1]:
# download the dataset from MNIST

from fastai.vision.all import *

path = untar_data(URLs.MNIST_SAMPLE)
path

<div><progress max="3214948" value="3219456"></progress> 100.14% [3219456/3214948 00:00&lt;00:00]</div>

Path('/root/.fastai/data/mnist_sample')

In [2]:
# let's look at the dataset directory

(path/'train').ls()

[Path('/root/.fastai/data/mnist_sample/train/7'), Path('/root/.fastai/data/mnist_sample/train/3')]

In [3]:
# open one image from training dataset of 3

three_path = (path/'train'/'3').ls()[0]
img = PILImage.create(three_path)
img

In [4]:
# conver the image 'RGB' to 'L'
img_gray = img.convert('L')

In [5]:
# since a neural network never sees a image it just see numbers
tensor(img_gray)

tensor([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
           0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,   0,   0, 113, 125, 125, 232, 254, 254,
         187, 160, 125, 106,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0],
        [  0,   0,   0,   0,   0,   0,  52, 17

In [6]:
# making the number easier for the neural network
img_tensor = tensor(img_gray).float()/255
img_tensor.shape

torch.Size([28, 28])

In [7]:
# flatten the image
flat_img = img_tensor.view(-1)
flat_img.shape

torch.Size([784])

In [8]:
# Building our first fake neuron
weights = torch.randn(784)
weights.shape

torch.Size([784])

In [9]:
# make a prediction
prediction = (flat_img * weights).sum()
prediction

tensor(4.1876)

In [10]:
# create the correct answer
label = tensor(1.)
label

tensor(1.)

In [11]:
# compare prediction with truth
loss = (prediction - label)**2
loss

tensor(10.1610)

In [12]:
# let's make learning possible
weights.requires_grad_()
weights.requires_grad
# Please watch these weights carefully

True

In [13]:
# let's rebuild everything properly
weights = torch.randn(784, requires_grad=True)
prediction = (flat_img * weights).sum()
label = tensor(1.)
loss = (prediction - label)**2
loss

tensor(649.2347, grad_fn=<PowBackward0>)

In [14]:
# somthing magical is going to happen here
loss.backward()
# How much each weight contributed to the loss

In [15]:
weights.grad

tensor([ -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,
         -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,
         -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,
         -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,
         -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,
         -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,
         -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,
         -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,
         -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,
         -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,
         -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,
         -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,
         -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.0000,  -0.00

In [16]:
# run the same code again
weights = torch.randn(784, requires_grad=True)
prediction = (flat_img * weights).sum()
label = tensor(1.)
loss = (prediction - label)**2
loss.backward()

In [17]:
weights.grad.shape

torch.Size([784])

In [18]:
weights.grad[:10]

tensor([-0., -0., -0., -0., -0., -0., -0., -0., -0., -0.])

In [19]:
flat_img[:20]

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [20]:
(weights.grad != 0).sum()

tensor(207)

In [21]:
# save current loss
old_loss = loss.item()
old_loss

3.4955122470855713

In [22]:
# update the weights

# learning rate = step size
# lr = 0.01 
lr = 0.0001


with torch.no_grad():
    weights -= lr * weights.grad

In [23]:
# make a new prediction
prediction = (flat_img * weights).sum()
loss = (prediction - label)**2
print(f"old_loss {old_loss}")
print(f"loss {loss}")
loss

old_loss 3.4955122470855713
loss 3.3022079467773438


tensor(3.3022, grad_fn=<PowBackward0>)

In [24]:
# frist training loop
weights = torch.randn(784, requires_grad = True)
bias = torch.randn(1, requires_grad=True)
label = tensor(1.)
lr = 0.0001
for i in range(20):
    prediction = (flat_img * weights).sum() + bias
    loss = (prediction - label)**2
    loss.backward()
    with torch.no_grad():
        weights -= lr * weights.grad
        bias -= lr * bias.grad

    weights.grad.zero_() # erase old gradients before calculating new gradients
    bias.grad.zero_()
    print(f"Step {i:2d} | Loss = {loss.item():.4f}")

Step  0 | Loss = 17.3342
Step  1 | Loss = 16.3688
Step  2 | Loss = 15.4572
Step  3 | Loss = 14.5964
Step  4 | Loss = 13.7834
Step  5 | Loss = 13.0158
Step  6 | Loss = 12.2909
Step  7 | Loss = 11.6064
Step  8 | Loss = 10.9600
Step  9 | Loss = 10.3496
Step 10 | Loss = 9.7732
Step 11 | Loss = 9.2289
Step 12 | Loss = 8.7149
Step 13 | Loss = 8.2296
Step 14 | Loss = 7.7712
Step 15 | Loss = 7.3384
Step 16 | Loss = 6.9297
Step 17 | Loss = 6.5438
Step 18 | Loss = 6.1794
Step 19 | Loss = 5.8352


**So far we have done all the stuff for one image, now it's time to do it for multiple image.**
A real model learns from many examples

In [25]:
# Load several image
threes = (path/'train'/'3').ls()[:20]
sevens = (path/'train'/'3').ls()[:20]

len(threes), len(sevens)

(20, 20)

In [26]:
# Create a dataset
xs = []
ys = []

for p in threes:
    img = PILImage.create(p).convert('L')
    x = tensor(img).float()/255
    x = x.view(-1)

    xs.append(x)
    ys.append(1.)

for p in sevens:
    img = PILImage.create(p).convert('L')
    x = tensor(img).float()/255
    x = x.view(-1)

    xs.append(x)
    ys.append(0.)

In [27]:
# stack everything
x_train = torch.stack(xs)
y_train = tensor(ys)

In [28]:
print(x_train.shape)
print(y_train.shape)

torch.Size([40, 784])
torch.Size([40])


In [29]:
weights = torch.randn(784, requires_grad = True)
bias = torch.randn(1, requires_grad = True)
prediction = x_train @ weights + bias
prediction.shape

torch.Size([40])

In [30]:
prediction[:10]

tensor([ -7.6186,  -3.0381, -10.6102, -11.7405,  -3.0667, -14.3944, -10.9484,
         -7.2066,  -5.3313,  -9.7621], grad_fn=<SliceBackward0>)

In [31]:
# calculating the loss
loss = ((prediction - y_train)**2).mean()
loss

tensor(87.2440, grad_fn=<MeanBackward0>)

**It's time to train on all 40 Image**

In [32]:
weights = torch.randn(784, requires_grad = True)
bias = torch.randn(1, requires_grad = True)

lr = 0.0001
for i in range(20):
    prediction = x_train @ weights + bias
    loss = ((prediction - y_train)**2).mean() # since we are doing it for 40 image

    loss.backward()

    with torch.no_grad():
        weights -= lr * weights.grad
        bias -= lr * bias.grad

    weights.grad.zero_()
    bias.grad.zero_()
    print(f"Step {i:2d} | Loss = {loss.item():.4f}")

Step  0 | Loss = 46.4065
Step  1 | Loss = 45.9991
Step  2 | Loss = 45.6010
Step  3 | Loss = 45.2121
Step  4 | Loss = 44.8320
Step  5 | Loss = 44.4606
Step  6 | Loss = 44.0976
Step  7 | Loss = 43.7429
Step  8 | Loss = 43.3961
Step  9 | Loss = 43.0572
Step 10 | Loss = 42.7259
Step 11 | Loss = 42.4021
Step 12 | Loss = 42.0855
Step 13 | Loss = 41.7761
Step 14 | Loss = 41.4735
Step 15 | Loss = 41.1776
Step 16 | Loss = 40.8883
Step 17 | Loss = 40.6054
Step 18 | Loss = 40.3288
Step 19 | Loss = 40.0582


**Now let's mess around with mutlitple neural networks**

In [33]:
weights1 = torch.randn(784, 30, requires_grad = True)
bias1 = torch.randn(30, requires_grad = True)

hidden = x_train @ weights1 + bias1

hidden.shape

torch.Size([40, 30])

In [34]:
weights2 = torch.randn(30,1, requires_grad=True)
bias2 = torch.randn(1, requires_grad=True)

hidden = x_train @ weights1 + bias1
hidden = hidden.clamp(min=0)

output = hidden @ weights2 + bias2
output.shape

torch.Size([40, 1])

In [35]:
y_train.shape

torch.Size([40])

In [36]:
y_train = y_train.unsqueeze(1) # adds a dimension
y_train.shape

torch.Size([40, 1])

In [37]:
# train the whole network
lr = 0.0001

for i in range(20):

    hidden = x_train @ weights1 + bias1

    hidden = hidden.clamp(min=0)

    output = hidden @ weights2 + bias2

    loss = ((output - y_train)**2).mean()

    loss.backward()

    with torch.no_grad():
        weights1 -= lr * weights1.grad
        bias1 -= lr * bias1.grad

        weights2 -= lr * weights2.grad
        bias2 -= lr * bias2.grad

    weights1.grad.zero_()
    bias1.grad.zero_()

    weights2.grad.zero_()
    bias2.grad.zero_()

    print(f"Step {i:2d} | Loss = {loss.item():.4f}")

Step  0 | Loss = 9312.0645
Step  1 | Loss = 1845.3483
Step  2 | Loss = 693.5563
Step  3 | Loss = 421.3320
Step  4 | Loss = 345.8057
Step  5 | Loss = 316.4443
Step  6 | Loss = 299.1841
Step  7 | Loss = 285.6515
Step  8 | Loss = 273.5897
Step  9 | Loss = 262.3784
Step 10 | Loss = 251.8234
Step 11 | Loss = 241.8444
Step 12 | Loss = 232.3934
Step 13 | Loss = 223.4325
Step 14 | Loss = 214.9440
Step 15 | Loss = 206.8959
Step 16 | Loss = 199.2457
Step 17 | Loss = 191.9687
Step 18 | Loss = 185.0416
Step 19 | Loss = 178.4435


**Entire training Loop in Plain English.**
1. Use the current weights and biases to make predictions
2. Compare predictions with the correct labels
3. Calculate the loss (how wrong we are)
4. Run backward() to calculate gradients
5. Update weights and biases using the gradients
6. Clear gradients so they don't accumulate
7. Record/print the loss
8. Repeat for the next epoch

In [39]:
# code 
class myLearner:  
    def __init__(self, x_train, y_train, weights1, bias1, weights2, bias2, lr):
        self.x_train = x_train
        self.y_train = y_train
        self.weights1 = weights1
        self.bias1 = bias1
        self.weights2 = weights2
        self.bias2 = bias2
        self.lr = lr

    def fit(self, epochs):
        for i in range(epochs):
            hidden = self.x_train @ self.weights1 + self.bias1

            hidden = hidden.clamp(min=0)
        
            output = hidden @ self.weights2 + self.bias2
        
            loss = ((output - self.y_train)**2).mean()
        
            loss.backward()
        
            with torch.no_grad():
                self.weights1 -= self.lr * self.weights1.grad
                self.bias1 -= self.lr * self.bias1.grad
        
                self.weights2 -= self.lr * self.weights2.grad
                self.bias2 -= self.lr * self.bias2.grad
        
            self.weights1.grad.zero_()
            self.bias1.grad.zero_()
        
            self.weights2.grad.zero_()
            self.bias2.grad.zero_()
        
            print(f"Step {i:2d} | Loss = {loss.item():.4f}")

    def predict(self, x):
        with torch.no_grad():
            hidden = x @ self.weights1 + self.bias1
            hidden = hidden.clamp(min=0)
            output = hidden @ self.weights2 + self.bias2
            output = output.item()
        if output > 0.5:
            return 3
        else:
            return 7
        
learn = myLearner(
    x_train, 
    y_train, 
    weights1, 
    bias1, 
    weights2, 
    bias2, 
    lr
)

learn.fit(20)
# x should be flattened if it's a 2D image, e.g. (28x28 → 784
x = image.flatten().float()/255  
pred = learn.predict(x)

Step  0 | Loss = 172.1350
Step  1 | Loss = 166.0759
Step  2 | Loss = 160.2988
Step  3 | Loss = 154.7863
Step  4 | Loss = 149.5178
Step  5 | Loss = 144.4855
Step  6 | Loss = 139.6767
Step  7 | Loss = 135.0800
Step  8 | Loss = 130.6832
Step  9 | Loss = 126.4751
Step 10 | Loss = 122.4457
Step 11 | Loss = 118.5853
Step 12 | Loss = 114.8808
Step 13 | Loss = 111.3197
Step 14 | Loss = 107.9074
Step 15 | Loss = 104.6306
Step 16 | Loss = 101.4827
Step 17 | Loss = 98.4645
Step 18 | Loss = 95.5665
Step 19 | Loss = 92.7792
